.Dd May 19, 2018
.Dt POMFU 1
.Os
.Sh NAME
.Nm pomfu
.Nd upload files to pomf clones
.Sh SYNOPSIS
.Nm pomfu
.Op Fl Hln
.Op Fl s Ar key
.Op Ar
.Sh DESCRIPTION
.Nm
uploads one or more files to pomf-compatible servers.
These are stored internally within the binary, but can be updated or added via a configuration file, as described in the
.Sx CONFIGURATION
section.
.Pp
If no files are specified,
.Nm
reads from the standard input.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl H
When randomly choosing a server, require that it supports uploading HTML files.
.It Fl l
Print all servers that
.Nm
knows about and exit.
.It Fl n
Prevent
.Nm
from reading it's configuration file.
See
.Xr pomfu 5 .
.It Fl s Ar key
Forces
.Nm
to use a specific pomf-server based on a
.Em key .
To find out what keys
.Nm
knows about, use
.Li -l .
.El
.Sh SEE ALSO
.Xr ppomf 1 ,
.Xr pomfu 5
.Sh AUTHORS
.An -nosplit
.An Xatasan Aq Mt xatasan@firemail.cc
